---
title: "beacons"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{beacons}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

## Beacons

Currently, the only beacon supported is the [National Institute of Standards and Technology (NIST) Interoperable Randomness Beacon (v2.0)](https://csrc.nist.gov/projects/interoperable-randomness-beacons/beacon-20) developed by the Cryptographic Technology group at NIST, the same department that developed the [Secure Hash Algorithm (SHA)](https://en.wikipedia.org/wiki/Secure_Hash_Algorithms) and hosted the competition that resulted in the development of the [Advanced Encryption Standard (AES)](https://en.wikipedia.org/wiki/Advanced_Encryption_Standard).

<details>
<summary> More on the NIST Beacon </summary>
The NIST beacon v2.0 issues a 'pulse' every 60 seconds which can be accessed by a public API returning a JSON data object which includes metadata about the pulse as well as a fresh random number. 

The main security feature that the NIST beacon employs that is relevant for the typical user of this package (there are many beyond the scope of this documentation) is hash-chaining:

* Each pulse is part of a chain. Every pulse provides a random number generated internally that is then combined with all of the metadata about the chain (including among other things the previous pulse's output) to produce the final output. 
* As a result, any attempt to alter the record of a previous pulse will be inconsistent with all future pulses in that chain
    * This does not prevent a motivated agent with the ability to alter **all** records in the NIST database from spoofing a historical record, but it does mean that any alterations to the NIST database can be detected as long as an external trusted copy of that chain is preserved
*  The default chain index currently used is chain 2 which started in 2022.

 **Resources:**

* [NIST Beacon info page](https://csrc.nist.gov/projects/interoperable-randomness-beacons)
* [NIST Beacon simple API documentation](https://csrc.nist.gov/Projects/interoperable-randomness-beacons/beacon-20) 
* The formal schema for the v2.0 beacon can be found in `/inst/extdata/beacon_schemas/NIST_v_2-0_schema.xsd`
* The formal reference manual can be found [here](https://doi.org/10.6028/NIST.IR.8213-draft).
    * This document is both highly technical document and oddly vauge in that it describes in depth both the current NIST beacon version's API but also what properties randomness beacons ought to have. A much more approachable and streamlined explanation can be found in presentation slides posted by one of the manual's authors [here](https://csrc.nist.gov/csrc/media/Presentations/2024/web3rand-pulses-of-unpredictability/images-media/20240618-W3Rand-Virtual-Workshop-NIST-Ref-Rand-Beacons.pdf)

There are other open source client libraries for the NIST Beacon that I've not yet used, but may be worth checking out:

* Python: [nistbeacon](https://github.com/urda/nistbeacon) 
* Javascript: [nist-randomness-beacon](https://github.com/chainpoint/nist-randomness-beacon)


</details>

<details>
<summary> Future directions for new Beacons</summary>
A major limitation of the current alpha version of `beacr` is relying on only one randomness beacon. The developers of NIST's beacon themselves suggest that mixing (or _`beacr::swirl`ing_) beacons together provide a more robust seed generation method in the event that any one beacon becomes unreliable. In future versions, I hope to implement additional beacons, and I welcome contributions to this end. Other beacons available at the moment are:

* [Distributed Randomness Beacon (drand)](https://drand.love/) from the [League of Entropy](https://blog.cloudflare.com/league-of-entropy/)
    * drand has client libraries for accessing their beacon via [Go](https://github.com/drand/drand) and [Javascript](https://github.com/drand/drand-client), but not R (to my knowledge)
* [The University of Colorado Boulder's CURBy (CU Randomness Beacon)](https://random.colorado.edu/)
    * CURBy has an official [Javascript](https://github.com/buff-beacon-project/curby-js-client) client library, but no library for R (to my knowledge)

If you wish to contribute to this project, adding additional beacons is a great place to start.
</details>
